### ISSUE TITLE
Allow using /min and /nosplash switches when starting revit process

### ISSUE THREAD

**Issue by eirannejad** [hdm-dt-fb/rvt_model_services#5]
```
/language <language code such as ENU> – Set user interface language.
/max – Start the session maximised.
/min – Start the session minimised.
/nosplash – Suppress the splash screen.
/viewer – Launch Revit in viewer mode.
```

**Comment by fbe-work** [comment]
Oh nice, thanks for point out! 
I was not aware of those and need to toy around with them! 
/nosplash sounds like it should be default.

**Comment by fbe-work** [comment]
ok I implemented '--rvt_args ' as optional argument, so you can pass things like '/nosplash' 
I still need to handle multiple of those..

**Comment by fbe-work** [comment]
hmm, it seems like rvt ignores the /nosplash /viewer and other options as soon as it is running in journal mode. If this is different on your machine please let me know. 
from an interactive session you could try: 
```python
# this accepts the options, since it has no journal to run:
prc_opt = psutil.Popen([rvt_install_path, "/nosplash", "/viewer"], cwd=paths["root_dir"],stdout=subprocess.PIPE, stderr=subprocess.PIPE)
# this ignores the options, since it runs a journal: 
prc_jrn = psutil.Popen([rvt_install_path, "/nosplash", "/viewer" , journal_file_path], cwd=paths["root_dir"],stdout=subprocess.PIPE, stderr=subprocess.PIPE)
```
I will (sadly) remove the docopt options as it does not seem to work..

**Comment by eirannejad** [comment]
Same here. Ignored. And doesn't record minimize maximize in the journal as an action, just as mouse moves and mouse clicks)

```vb
' Minimize Revit journal entries - needs to know what is the monitor resolution
 Jrn.MouseMove    0 ,   1675 ,     65
 Jrn.LButtonDown    1 ,   1675 ,     65
 Jrn.LButtonUp    0 ,   1675 ,     65

```

**Comment by thazell** [comment]
FYI... in journal mode user settings are also reset.  Double Click setting, Keyboard Shortcuts, User interface Clicks.  In a Revit launcher I modified that's in AHK.   I stored the user settings in a subfolder before restoring them.  Just fyi.

**Comment by eirannejad** [comment]
Oh gosh. As if it's a different program all together. Damn bad software design.

**Comment by fbe-work** [comment]
@eirannejad @thazell thanks for testing comments! 
having it run nosplash+minimized would have been a real treat, but oh well.. 
@thazell thanks for mentioning revit launcher I had not heard of it but looking at ahk brings back some good memories.. (-;

**Comment by fbe-work** [comment]
@eirannejad just found out that `/viewer` is actually not ignored, so I added it as an optional switch..

**Comment by enscmlygc** [comment]
are there any ways to change default revit splash screen image with my own any .jpeg image? unfortunately just i found an information about /nosplash..
